// <auto-generated />
using System;
using E_Shelf_WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace E_Shelf_WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221011203212_Seed Data")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Shelf_WebApi.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2022, 10, 8, 23, 32, 11, 781, DateTimeKind.Local).AddTicks(2983),
                            Name = "Computer",
                            Price = 15000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2022, 9, 11, 23, 32, 11, 782, DateTimeKind.Local).AddTicks(6790),
                            Name = "SmartPhone",
                            Price = 15000m,
                            Stock = 500
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2022, 8, 12, 23, 32, 11, 782, DateTimeKind.Local).AddTicks(6816),
                            Name = "Mouse",
                            Price = 15m,
                            Stock = 1000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
